project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - individuales.qmd
    - grupales.qmd
    - ss policia.qmd
    - oferta.qmd

website:
  title: "Observatorio de Medicina Complementaria (2019-2024)"
  navbar:
    left:
      - href: index.qmd
        text: "Inicio"
      - href: individuales.qmd
        text: "Atenciones Individuales (MINSA)"
      - href: grupales.qmd
        text: "Actividades Grupales (MINSA)"
      - href: ss policia.qmd
        text: "Actividades Individuales (SALUDPOL)"
      - href: oferta.qmd
        text: "Oferta de servicios"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    self-contained: true